### ISSUE TITLE
Hangs during build.

### ISSUE THREAD

**Issue by BonaBeavis** [SmartDataAnalytics/SparqlIntegrate#1]
Dependency http://download.java.net/maven/2/junit/junit/4.12/junit-4.12.jar does a 404

**Comment by BonaBeavis** [comment]
https://github.com/SmartDataAnalytics/SparqlIntegrate/blob/780fd71837e9cd8ed33201424378f349e7dbeb5d/pom.xml#L398

**Comment by Aklakan** [comment]
I removed the repo; probably a copy and paste mistake.
Please try again.

**Comment by BonaBeavis** [comment]
Works now
