### ISSUE TITLE
Handle mixed construct queries

### ISSUE THREAD

**Issue by BonaBeavis** [SmartDataAnalytics/SparqlIntegrate#6]
A construct query could return triples and/or quads. In the "and/or" case a mixed output is returned. I think it would be better to return only quads if a quad statement exist. So the output could have a "filetype" n-quads.

**Comment by Aklakan** [comment]
Hm, it is currently a disadvantage, that queries are parsed and executed in the order the appear.
It would certainly be more convenient if the queries were checked in advance.

That said, if you specify a quad based output format, such as `sparql-integrate --w=N-Quads/utf-8` it would work with the mixed case as n-quads is a superset of n-triples.

**Comment by Aklakan** [comment]
Using trig or n-quads reduces to turtle and n-triples if no named graphs are used. So this specific issue can be considered as resolved. Analyzing query types in advance is a different matter.
